- name: Deploying war into Apache Tomcat
  hosts: localhost
  connection: local
  become: true
  become_user: root
  vars: 
    tomcat_port: 8082
  
  tasks:
    - name: Deploy java war into Apache tomcat server
      import_role:
        name: ansible_tomcat_roles        
        
